### ISSUE TITLE
[enhancement] Focus in middle

### ISSUE THREAD

**Issue by chrismatheson** [toshsharma/brackets-bookmarks#2]
Just a suggestion for a small enhancement.

when moving to a bookmark that line should be in the middle of the editor (vertically)

really great job though, i think its a solid extension.

**Comment by toshsharma** [comment]
Thanks for the suggestion. I think it might be a little disconcerting if the editor moved around even when the bookmarked line was already in the current viewport. Instead, I've added a flash for the bookmarked line - i.e. when moving to a bookmarked line, the line's background will flash for an instant, letting the user identify the location in the editor's viewport.
